### ISSUE TITLE
SEServerExtender soft stopping server/not restarting as with a hard crash.

### ISSUE THREAD

**Issue by aandrew132** [SEServerExtender/SEServerExtender#93]
I have been having an issue with the server seeming to soft stop without the extender actually crashing/restarting with restartoncrash set. this has been an issue as it means i have to babysit the server now to make sure it's still running properly. most likely something im doing wrong since this is a mod heavy server. but in the case that it isnt, i've upoaded the server log for review.

https://www.dropbox.com/s/kyspmjkoaz7fmqx/SpaceEngineersDedicated%20107152040.txt?dl=0

If this issue is not related to SESE, please feel free to berate me and call me an idiot.

**Comment by aandrew132** [comment]
this may actually be an essentials issue.

**Comment by aandrew132** [comment]
Issue might have been self resolved by updating VC++2012 on server.

**Comment by dodexahedron** [comment]
VC++ 2012 is not related to SESE or Essentials in any way, as neither of these programs are written in C++.
It also didn't fix the problem you're seeing because the problem you're seeing is caused by a change that was made to SE itself.
The problem can't really be fixed in any good way in SESE, because the root of the problem is that certain SE methods are not thread safe.
I'm going to close this issue, since there's nothing I can do about it and it's really a KSH problem to fix.
